apiVersion: apps/v1
kind: Deployment

metadata:
  name: cicd-demo

spec:
  replicas: 2
  
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: cicd-demo

  template:
    metadata:
      labels:
        app: cicd-demo

    spec:
      containers:
        - name: cicd-demo

          image: ghcr.io/shivashankar-bansode96/cicd-demo:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20